/**
 * Import a ChompChores data.json snapshot into a NEW Supabase project.
 *
 * SAFETY (kids are live on Docker JSON):
 * - Does NOT talk to Docker /data by default.
 * - Default mode is dry-run + SQL file generation only.
 * - --apply requires SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY and explicit flag.
 * - Never deletes or modifies the source JSON file.
 *
 * Usage:
 *   node --experimental-strip-types import-json-to-pg.ts --input ../exports/snapshot.json
 *   node --experimental-strip-types import-json-to-pg.ts --input ./snapshot.json --apply
 *
 * Take a snapshot first (manual, offline from kids' usage window):
 *   curl -s http://127.0.0.1:3000/data > exports/snapshot-$(date +%Y%m%d).json
 * Then run import against that COPY — keep Docker running unchanged until you cut over.
 */

import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type JsonUser = {
  id: string;
  username: string;
  passwordHash?: string;
  roles?: string[];
  role?: string;
  soundPref?: string;
  createdAt?: string;
};

type JsonState = {
  users?: JsonUser[];
  chores?: any[];
  rewards?: any[];
  oneTimeTasks?: any[];
  tasks?: any[];
  calFeeds?: any[];
  adminLog?: any[];
  settings?: { dailyTarget?: number; penaltyPts?: number; pin?: string };
  userProgress?: Record<
    string,
    {
      points?: number;
      checked?: Record<string, boolean>;
      lastResetDate?: string | null;
      history?: any[];
    }
  >;
};

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
function has(flag: string) {
  return process.argv.includes(flag);
}

function rolesOf(u: JsonUser): string[] {
  if (Array.isArray(u.roles) && u.roles.length) return u.roles;
  if (u.role === "admin") return ["admin"];
  if (u.role === "task") return ["task"];
  return ["chore"];
}

function emailFor(username: string, householdSlug: string) {
  return `${username.toLowerCase()}@${householdSlug}.chompchores.local`;
}

async function main() {
  const input = arg("--input");
  const householdName = arg("--household") || "Goyal Family";
  const householdSlug = (arg("--slug") || "goyal").toLowerCase().replace(/[^a-z0-9]+/g, "");
  const defaultPassword = arg("--default-password") || "ChangeMeNow!";
  const outDir = resolve(arg("--out") || resolve(dirname(fileURLToPath(import.meta.url)), "../exports/import-out"));
  const apply = has("--apply");

  if (!input) {
    console.error(`Missing --input path to a JSON snapshot COPY.

Kids' live Docker app must stay untouched.
1) Snapshot when convenient:
     mkdir -p exports
     curl -s http://127.0.0.1:3000/data > exports/snapshot.json
2) Dry-run import (default):
     npm run import-json -- --input ../exports/snapshot.json
3) Only after a NEW Supabase project is ready:
     SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... npm run import-json -- --input ../exports/snapshot.json --apply`);
    process.exit(1);
  }

  const abs = resolve(input);
  const raw = JSON.parse(readFileSync(abs, "utf8")) as JsonState;
  const users = raw.users || [];
  if (!users.length) {
    console.error("No users in snapshot");
    process.exit(1);
  }

  mkdirSync(outDir, { recursive: true });

  const householdId = randomUUID();
  const idMap: Record<string, string> = {}; // legacy user id → new uuid
  for (const u of users) {
    idMap[u.id] = randomUUID();
  }

  const summary = {
    source: abs,
    householdId,
    householdName,
    users: users.map((u) => ({
      legacyId: u.id,
      username: u.username,
      newId: idMap[u.id],
      email: emailFor(u.username, householdSlug),
      roles: rolesOf(u),
    })),
    counts: {
      chores: (raw.chores || []).length,
      rewards: (raw.rewards || []).length,
      oneTimeTasks: (raw.oneTimeTasks || []).length,
      tasks: (raw.tasks || []).length,
      calFeeds: (raw.calFeeds || []).length,
      adminLog: (raw.adminLog || []).length,
      userProgressKeys: Object.keys(raw.userProgress || {}).length,
    },
    apply,
    note: "Live Docker JSON is NOT modified by this script.",
  };

  writeFileSync(resolve(outDir, "id-map.json"), JSON.stringify({ householdId, idMap, summary }, null, 2));

  // Build SQL for review (auth users still need Admin API on --apply)
  const sql: string[] = [];
  sql.push("-- Generated by import-json-to-pg.ts — review before apply");
  sql.push(`-- source: ${abs}`);
  sql.push("begin;");
  sql.push(
    `insert into public.households (id, name) values ('${householdId}', '${householdName.replace(/'/g, "''")}');`
  );
  sql.push(
    `insert into public.household_settings (household_id, daily_target, penalty_pts) values ('${householdId}', ${Number(raw.settings?.dailyTarget ?? 15)}, ${Number(raw.settings?.penaltyPts ?? 5)});`
  );
  sql.push("-- profiles require matching auth.users rows (created by --apply via Auth Admin API)");
  for (const u of users) {
    const nid = idMap[u.id];
    const roles = rolesOf(u).map((r) => `'${r}'`).join(",");
    sql.push(
      `insert into public.profiles (id, household_id, username, roles, sound_pref, legacy_id) values ('${nid}', '${householdId}', '${u.username.replace(/'/g, "''")}', array[${roles}]::public.app_role[], '${u.soundPref === "off" ? "off" : "on"}', '${u.id}');`
    );
  }

  const mapAssignee = (legacy?: string) => {
    if (!legacy) return null;
    return idMap[legacy] || null;
  };

  for (const c of raw.chores || []) {
    const aid = mapAssignee(c.userId);
    if (!aid) continue;
    const group = c.group ? `'${String(c.group).replace(/'/g, "''")}'` : "null";
    sql.push(
      `insert into public.chores (id, household_id, assignee_id, name, pts, group_key) values ('${c.id}', '${householdId}', '${aid}', '${String(c.name).replace(/'/g, "''")}', ${Number(c.pts)}, ${group});`
    );
  }

  for (const r of raw.rewards || []) {
    const aid = mapAssignee(r.userId);
    if (!aid) continue;
    const type = r.type === "timer" ? "timer" : "standard";
    const redeem = r.redeemType === "onetime" ? "onetime" : "persistent";
    sql.push(
      `insert into public.rewards (id, household_id, assignee_id, name, type, redeem_type, cost, timer_pts, timer_hours, times_used, last_used) values ('${r.id}', '${householdId}', '${aid}', '${String(r.name).replace(/'/g, "''")}', '${type}', '${redeem}', ${Number(r.cost || 0)}, ${r.timerPts ?? "null"}, ${r.timerHours ?? "null"}, ${Number(r.timesUsed || 0)}, ${r.lastUsed ? `'${r.lastUsed}'` : "null"});`
    );
  }

  for (const t of raw.oneTimeTasks || []) {
    const aid = mapAssignee(t.userId);
    if (!aid) continue;
    sql.push(
      `insert into public.one_time_tasks (id, household_id, assignee_id, name, due_date, pts, priority, done) values ('${t.id}', '${householdId}', '${aid}', '${String(t.name).replace(/'/g, "''")}', '${t.date}', ${Number(t.pts || 0)}, '${t.priority || "normal"}', ${t.done ? "true" : "false"});`
    );
  }

  for (const [legacyUid, prog] of Object.entries(raw.userProgress || {})) {
    const uid = idMap[legacyUid];
    if (!uid) continue;
    const checked = JSON.stringify(prog.checked || {}).replace(/'/g, "''");
    sql.push(
      `insert into public.user_progress (user_id, household_id, points, checked, last_reset_date) values ('${uid}', '${householdId}', ${Number(prog.points || 0)}, '${checked}'::jsonb, ${prog.lastResetDate ? `'${prog.lastResetDate}'` : "null"});`
    );
    for (const day of prog.history || []) {
      const dayId = randomUUID();
      sql.push(
        `insert into public.history_days (id, user_id, day, daily_earned, daily_spent, penalty) values ('${dayId}', '${uid}', '${day.date}', ${Number(day.dailyEarned || 0)}, ${Number(day.dailySpent || 0)}, ${Number(day.penalty || 0)});`
      );
      for (const e of day.entries || []) {
        const typ = String(e.type || "chore").replace(/'/g, "''");
        sql.push(
          `insert into public.history_entries (history_day_id, type, label, pts, entry_time) values ('${dayId}', '${typ}', '${String(e.label || "").replace(/'/g, "''")}', ${Number(e.pts || 0)}, '${String(e.time || "").replace(/'/g, "''")}');`
        );
      }
    }
  }

  for (const t of raw.tasks || []) {
    const oid = mapAssignee(t.userId);
    if (!oid) continue;
    sql.push(
      `insert into public.personal_tasks (id, household_id, owner_id, name, description, priority, status, date_added, eta, reminder, alarm, completed_at) values ('${t.id}', '${householdId}', '${oid}', '${String(t.name).replace(/'/g, "''")}', ${t.desc ? `'${String(t.desc).replace(/'/g, "''")}'` : "null"}, '${t.priority || "medium"}', '${t.status || "pending"}', '${t.dateAdded}', ${t.eta ? `'${t.eta}'` : "null"}, ${t.reminder ? `'${t.reminder}'` : "null"}, ${t.alarm ? `'${t.alarm}'` : "null"}, ${t.completedAt ? `'${t.completedAt}'` : "null"});`
    );
  }

  for (const f of raw.calFeeds || []) {
    const oid = mapAssignee(f.userId);
    if (!oid) continue;
    const events = JSON.stringify(f.events || []).replace(/'/g, "''");
    sql.push(
      `insert into public.cal_feeds (id, household_id, owner_id, name, url, color, events) values ('${f.id}', '${householdId}', '${oid}', '${String(f.name).replace(/'/g, "''")}', '${String(f.url).replace(/'/g, "''")}', '${f.color || "#6c47e8"}', '${events}'::jsonb);`
    );
  }

  for (const a of raw.adminLog || []) {
    sql.push(
      `insert into public.admin_log (household_id, type, label, detail, day, entry_time) values ('${householdId}', '${String(a.type || "").replace(/'/g, "''")}', '${String(a.label || "").replace(/'/g, "''")}', ${a.detail ? `'${String(a.detail).replace(/'/g, "''")}'` : "null"}, '${a.date}', '${String(a.time || "").replace(/'/g, "''")}');`
    );
  }

  sql.push("commit;");
  const sqlPath = resolve(outDir, "import.sql");
  writeFileSync(sqlPath, sql.join("\n") + "\n");
  writeFileSync(resolve(outDir, "summary.json"), JSON.stringify(summary, null, 2));

  console.log(JSON.stringify(summary, null, 2));
  console.log(`\nWrote ${sqlPath}`);
  console.log(`Wrote ${resolve(outDir, "id-map.json")}`);

  if (!apply) {
    console.log("\nDry-run only. Live kids app untouched. Re-run with --apply when Supabase is ready.");
    return;
  }

  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error("--apply requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");
    process.exit(1);
  }

  const { createClient } = await import("@supabase/supabase-js");
  const supabase = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });

  // Create auth users first (so profiles FK succeeds)
  for (const u of users) {
    const newId = idMap[u.id];
    const email = emailFor(u.username, householdSlug);
    const { error } = await supabase.auth.admin.createUser({
      id: newId,
      email,
      password: defaultPassword,
      email_confirm: true,
      user_metadata: { username: u.username, legacy_id: u.id },
    });
    if (error && !String(error.message).includes("already")) {
      console.error("auth create failed", u.username, error.message);
      process.exit(1);
    }
    console.log("auth user", u.username, email);
  }

  // Execute SQL via rpc isn't available; use REST inserts instead of raw SQL file for apply path
  const { error: hErr } = await supabase.from("households").insert({ id: householdId, name: householdName });
  if (hErr) {
    console.error(hErr);
    process.exit(1);
  }
  await supabase.from("household_settings").insert({
    household_id: householdId,
    daily_target: Number(raw.settings?.dailyTarget ?? 15),
    penalty_pts: Number(raw.settings?.penaltyPts ?? 5),
    pin_hash: raw.settings?.pin
      ? createHash("sha256").update(String(raw.settings.pin)).digest("hex")
      : null,
  });

  for (const u of users) {
    const { error } = await supabase.from("profiles").insert({
      id: idMap[u.id],
      household_id: householdId,
      username: u.username,
      roles: rolesOf(u),
      sound_pref: u.soundPref === "off" ? "off" : "on",
      legacy_id: u.id,
    });
    if (error) {
      console.error("profile", u.username, error);
      process.exit(1);
    }
  }

  if ((raw.chores || []).length) {
    const rows = (raw.chores || [])
      .map((c) => {
        const aid = mapAssignee(c.userId);
        if (!aid) return null;
        return {
          id: c.id,
          household_id: householdId,
          assignee_id: aid,
          name: c.name,
          pts: c.pts,
          group_key: c.group || null,
        };
      })
      .filter(Boolean);
    const { error } = await supabase.from("chores").insert(rows as any);
    if (error) {
      console.error("chores", error);
      process.exit(1);
    }
  }

  if ((raw.rewards || []).length) {
    const rows = (raw.rewards || [])
      .map((r) => {
        const aid = mapAssignee(r.userId);
        if (!aid) return null;
        return {
          id: r.id,
          household_id: householdId,
          assignee_id: aid,
          name: r.name,
          type: r.type === "timer" ? "timer" : "standard",
          redeem_type: r.redeemType === "onetime" ? "onetime" : "persistent",
          cost: r.cost || 0,
          timer_pts: r.timerPts ?? null,
          timer_hours: r.timerHours ?? null,
          times_used: r.timesUsed || 0,
          last_used: r.lastUsed || null,
        };
      })
      .filter(Boolean);
    const { error } = await supabase.from("rewards").insert(rows as any);
    if (error) {
      console.error("rewards", error);
      process.exit(1);
    }
  }

  for (const [legacyUid, prog] of Object.entries(raw.userProgress || {})) {
    const uid = idMap[legacyUid];
    if (!uid) continue;
    const { error } = await supabase.from("user_progress").insert({
      user_id: uid,
      household_id: householdId,
      points: prog.points || 0,
      checked: prog.checked || {},
      last_reset_date: prog.lastResetDate || null,
    });
    if (error) {
      console.error("progress", error);
      process.exit(1);
    }
    for (const day of prog.history || []) {
      const dayId = randomUUID();
      const { error: dErr } = await supabase.from("history_days").insert({
        id: dayId,
        user_id: uid,
        day: day.date,
        daily_earned: day.dailyEarned || 0,
        daily_spent: day.dailySpent || 0,
        penalty: day.penalty || 0,
      });
      if (dErr) {
        console.error("history_days", dErr);
        process.exit(1);
      }
      const entries = (day.entries || []).map((e: any) => ({
        history_day_id: dayId,
        type: e.type,
        label: e.label,
        pts: e.pts || 0,
        entry_time: e.time || "",
      }));
      if (entries.length) {
        const { error: eErr } = await supabase.from("history_entries").insert(entries);
        if (eErr) {
          console.error("history_entries", eErr);
          process.exit(1);
        }
      }
    }
  }

  console.log("\nApply complete.");
  console.log(`Default password for imported users: ${defaultPassword}`);
  console.log("Change passwords immediately. Docker JSON app was NOT modified.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
